version: "3.9"

services:
  api:
    image: "dgapi"
    ports:
      - "8000:5000"
    volumes:
      - .:/dg
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"
    volumes:
      - dgredis:/data
volumes:
  dgredis:
