version: "3.9"

services:
  api:
    image: "geodapi"
    ports:
      - "8000:5000"
    volumes:
      - .:/dg
    environment:
      - PWD_HASHING=passlib         # [fake|passlib]
      - DB_ACCOUNTS=redis           # [inmem|redis]
      - DB_DISTANCES=redis          # [inmem|redis]
      - REDIS_HOST=redis
      - SEARCH_SERVICE=nominatim    # [fake|nominatim]
      - DISTANCE_SERVICE=geopy      # [fake|geopy]
  redis:
    image: "redis:alpine"
    volumes:
      - dgredis:/data
volumes:
  dgredis:
